apiVersion: apps/v1
kind: Deployment
metadata:
  name: unity-server-deployment
spec:
  replicas: 1  # 원하는 파드 수
  selector:
    matchLabels:
      app: unity-server
  template:
    metadata:
      labels:
        app: unity-server
    spec:
      containers:
      - name: unity-server-container
        image: 0fficeg2/tree-unity:v1  # Docker 이미지를 설정합니다.
        ports:
        - containerPort: 8000  # Unity 서버에서 사용하는 포트
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
