apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn-deployment
  labels:
    app: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coturn
  template:
    metadata:
      labels:
        app: coturn
    spec:
      hostNetwork: true
      containers:
      - name: coturn
        image: coturn/coturn
        args:
          - "--min-port=49160"
          - "--max-port=49200"
          - "--lt-cred-mech"
          - "--user=tree:tree"
          - "--realm=your-realm.com"
          - "--fingerprint"
          - "--verbose"
        ports:
          - containerPort: 3478
            protocol: TCP
          - containerPort: 3478
            protocol: UDP
          - containerPort: 5349
            protocol: TCP
          - containerPort: 5349
            protocol: UDP
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: coturn-service
  labels:
    app: coturn
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-udp-ports: "3478,5349,49160-49200"
spec:
  type: LoadBalancer
  selector:
    app: coturn
  ports:
    - name: turn-udp-3478
      protocol: UDP
      port: 3478
      targetPort: 3478
    - name: turn-udp-5349
      protocol: UDP
      port: 5349
      targetPort: 5349
    - name: turn-tcp-3478
      protocol: TCP
      port: 3478
      targetPort: 3478
    - name: turn-tcp-5349
      protocol: TCP
      port: 5349
      targetPort: 5349

